language: objective-c

branches:
 only:
 - master

xcode_project: Jolt.xcodeproj
xcode_scheme: Jolt
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

after_success:
  - bash <(curl -s https://codecov.io/bash)
