language: objective-c

branches:
 only:
 - master

#xcode_workspace: Jolt.xcworkspace
#xcode_scheme: Jolt
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

script:
  - xctool -workspace Jolt.xcworkspace -scheme Jolt build test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES

after_success:
  - bash <(curl -s https://codecov.io/bash)
