language: objective-c

branches:
 only:
 - master

#xcode_project: Jolt.xcodeproj
#xcode_scheme: Jolt
osx_image: xcode7
#xcode_sdk: iphonesimulator9.0

script:
  - xcodebuild -scheme Jolt -project Jolt.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.0' test

after_success:
  - bash <(curl -s https://codecov.io/bash)
