language: objective-c

branches:
 only:
 - master

osx_image: xcode7

script:
  - xcodebuild -scheme Jolt -project Jolt.xcodeproj -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6S,OS=9.0' test | xcpretty -c

after_success:
  - bash <(curl -s https://codecov.io/bash)
