language: objective-c

branches:
 only:
 - master

xcode_workspace: Jolt.xcworkspace
xcode_scheme: JoltTests
osx_image: xcode7
xcode_sdk: iphonesimulator9.0

#script:
#- xcodebuild clean build test -project Swifternalization.xcodeproj -scheme SwifternalizationTests
